name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Actualizado a v4 (recomendado)

      - name: Set up .NET
        uses: actions/setup-dotnet@v4 # Importante: Usar v4 para .NET 9
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        # Le decimos que busque en la carpeta Lab4-NadiaTorres
        run: dotnet restore Lab4-NadiaTorres

      - name: Build application
        # Le decimos que construya lo que est√° en la carpeta Lab4-NadiaTorres
        run: dotnet build Lab4-NadiaTorres --configuration Release
      
      - name: Publish application
        run: dotnet publish Lab4-NadiaTorres/Lab4-NadiaTorres/Lab4-NadiaTorres.csproj --configuration Release --output ./published

      - name: Deploy to server (ejemplo de despliegue)
        run: |
          # scp -r ./published username@server:/path/to/deploy
          echo "Listo para desplegar"
